package cn.tanziquan.produce.cole.data.domain;

import java.io.Serializable;
import java.util.Date;

public class AppRelease implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.webhooks_id
     *
     * @mbggenerated
     */
    private Integer webhooksId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.stage
     *
     * @mbggenerated
     */
    private Byte stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.is_delete
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.create_at
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.update_at
     *
     * @mbggenerated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_app_release
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.id
     *
     * @return the value of tb_app_release.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.id
     *
     * @param id the value for tb_app_release.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.app_id
     *
     * @return the value of tb_app_release.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.app_id
     *
     * @param appId the value for tb_app_release.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.webhooks_id
     *
     * @return the value of tb_app_release.webhooks_id
     *
     * @mbggenerated
     */
    public Integer getWebhooksId() {
        return webhooksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.webhooks_id
     *
     * @param webhooksId the value for tb_app_release.webhooks_id
     *
     * @mbggenerated
     */
    public void setWebhooksId(Integer webhooksId) {
        this.webhooksId = webhooksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.stage
     *
     * @return the value of tb_app_release.stage
     *
     * @mbggenerated
     */
    public Byte getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.stage
     *
     * @param stage the value for tb_app_release.stage
     *
     * @mbggenerated
     */
    public void setStage(Byte stage) {
        this.stage = stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.is_delete
     *
     * @return the value of tb_app_release.is_delete
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.is_delete
     *
     * @param isDelete the value for tb_app_release.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.create_at
     *
     * @return the value of tb_app_release.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.create_at
     *
     * @param createAt the value for tb_app_release.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.update_at
     *
     * @return the value of tb_app_release.update_at
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.update_at
     *
     * @param updateAt the value for tb_app_release.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}