package cn.tanziquan.produce.cole.data.domain;

import java.io.Serializable;

public class AppReleaseDevelop implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release_develop.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_app_release_develop
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release_develop.id
     *
     * @return the value of tb_app_release_develop.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release_develop.id
     *
     * @param id the value for tb_app_release_develop.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}