package cn.tanziquan.produce.cole.data.domain;

import java.io.Serializable;
import java.sql.Timestamp;

public class AppRelease implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.record_id
     *
     * @mbggenerated
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.stage
     *
     * @mbggenerated
     */
    private Byte stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.branch
     *
     * @mbggenerated
     */
    private String branch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.is_delete
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.created_at
     *
     * @mbggenerated
     */
    private Timestamp createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release.updated_at
     *
     * @mbggenerated
     */
    private Timestamp updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_app_release
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.id
     *
     * @return the value of tb_app_release.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.id
     *
     * @param id the value for tb_app_release.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.app_id
     *
     * @return the value of tb_app_release.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.app_id
     *
     * @param appId the value for tb_app_release.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.record_id
     *
     * @return the value of tb_app_release.record_id
     *
     * @mbggenerated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.record_id
     *
     * @param recordId the value for tb_app_release.record_id
     *
     * @mbggenerated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.stage
     *
     * @return the value of tb_app_release.stage
     *
     * @mbggenerated
     */
    public Byte getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.stage
     *
     * @param stage the value for tb_app_release.stage
     *
     * @mbggenerated
     */
    public void setStage(Byte stage) {
        this.stage = stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.branch
     *
     * @return the value of tb_app_release.branch
     *
     * @mbggenerated
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.branch
     *
     * @param branch the value for tb_app_release.branch
     *
     * @mbggenerated
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.is_delete
     *
     * @return the value of tb_app_release.is_delete
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.is_delete
     *
     * @param isDelete the value for tb_app_release.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.created_at
     *
     * @return the value of tb_app_release.created_at
     *
     * @mbggenerated
     */
    public Timestamp getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.created_at
     *
     * @param createdAt the value for tb_app_release.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release.updated_at
     *
     * @return the value of tb_app_release.updated_at
     *
     * @mbggenerated
     */
    public Timestamp getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release.updated_at
     *
     * @param updatedAt the value for tb_app_release.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }
}