package cn.tanziquan.produce.cole.data.domain;

import java.io.Serializable;
import java.sql.Timestamp;

public class AppReleaseDevelopServer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release_develop_server.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release_develop_server.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release_develop_server.hostName
     *
     * @mbggenerated
     */
    private String hostname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release_develop_server.runtime_status
     *
     * @mbggenerated
     */
    private Short runtimeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release_develop_server.is_delete
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release_develop_server.created_at
     *
     * @mbggenerated
     */
    private Timestamp createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_release_develop_server.updated_at
     *
     * @mbggenerated
     */
    private Timestamp updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_app_release_develop_server
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release_develop_server.id
     *
     * @return the value of tb_app_release_develop_server.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release_develop_server.id
     *
     * @param id the value for tb_app_release_develop_server.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release_develop_server.app_id
     *
     * @return the value of tb_app_release_develop_server.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release_develop_server.app_id
     *
     * @param appId the value for tb_app_release_develop_server.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release_develop_server.hostName
     *
     * @return the value of tb_app_release_develop_server.hostName
     *
     * @mbggenerated
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release_develop_server.hostName
     *
     * @param hostname the value for tb_app_release_develop_server.hostName
     *
     * @mbggenerated
     */
    public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release_develop_server.runtime_status
     *
     * @return the value of tb_app_release_develop_server.runtime_status
     *
     * @mbggenerated
     */
    public Short getRuntimeStatus() {
        return runtimeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release_develop_server.runtime_status
     *
     * @param runtimeStatus the value for tb_app_release_develop_server.runtime_status
     *
     * @mbggenerated
     */
    public void setRuntimeStatus(Short runtimeStatus) {
        this.runtimeStatus = runtimeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release_develop_server.is_delete
     *
     * @return the value of tb_app_release_develop_server.is_delete
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release_develop_server.is_delete
     *
     * @param isDelete the value for tb_app_release_develop_server.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release_develop_server.created_at
     *
     * @return the value of tb_app_release_develop_server.created_at
     *
     * @mbggenerated
     */
    public Timestamp getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release_develop_server.created_at
     *
     * @param createdAt the value for tb_app_release_develop_server.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_release_develop_server.updated_at
     *
     * @return the value of tb_app_release_develop_server.updated_at
     *
     * @mbggenerated
     */
    public Timestamp getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_release_develop_server.updated_at
     *
     * @param updatedAt the value for tb_app_release_develop_server.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }
}