package cn.tanziquan.produce.cole.data.domain;

import java.io.Serializable;
import java.util.Date;

public class ColeRequestBody implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cole_request_body.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cole_request_body.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cole_request_body.post_json
     *
     * @mbggenerated
     */
    private String postJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cole_request_body.create_at
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cole_request_body.id
     *
     * @return the value of tb_cole_request_body.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cole_request_body.id
     *
     * @param id the value for tb_cole_request_body.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cole_request_body.app_id
     *
     * @return the value of tb_cole_request_body.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cole_request_body.app_id
     *
     * @param appId the value for tb_cole_request_body.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cole_request_body.post_json
     *
     * @return the value of tb_cole_request_body.post_json
     *
     * @mbggenerated
     */
    public String getPostJson() {
        return postJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cole_request_body.post_json
     *
     * @param postJson the value for tb_cole_request_body.post_json
     *
     * @mbggenerated
     */
    public void setPostJson(String postJson) {
        this.postJson = postJson == null ? null : postJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cole_request_body.create_at
     *
     * @return the value of tb_cole_request_body.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cole_request_body.create_at
     *
     * @param createAt the value for tb_cole_request_body.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}