package cn.tanziquan.produce.cole.data.domain;

import java.io.Serializable;
import java.sql.Timestamp;

public class CorpAuthInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_corp_auth_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_corp_auth_info.corpid
     *
     * @mbggenerated
     */
    private String corpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_corp_auth_info.corp_name
     *
     * @mbggenerated
     */
    private String corpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_corp_auth_info.industry
     *
     * @mbggenerated
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_corp_auth_info.is_delete
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_corp_auth_info.created_at
     *
     * @mbggenerated
     */
    private Timestamp createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_corp_auth_info.updated_at
     *
     * @mbggenerated
     */
    private Timestamp updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_corp_auth_info.id
     *
     * @return the value of tb_corp_auth_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_corp_auth_info.id
     *
     * @param id the value for tb_corp_auth_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_corp_auth_info.corpid
     *
     * @return the value of tb_corp_auth_info.corpid
     *
     * @mbggenerated
     */
    public String getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_corp_auth_info.corpid
     *
     * @param corpid the value for tb_corp_auth_info.corpid
     *
     * @mbggenerated
     */
    public void setCorpid(String corpid) {
        this.corpid = corpid == null ? null : corpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_corp_auth_info.corp_name
     *
     * @return the value of tb_corp_auth_info.corp_name
     *
     * @mbggenerated
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_corp_auth_info.corp_name
     *
     * @param corpName the value for tb_corp_auth_info.corp_name
     *
     * @mbggenerated
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_corp_auth_info.industry
     *
     * @return the value of tb_corp_auth_info.industry
     *
     * @mbggenerated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_corp_auth_info.industry
     *
     * @param industry the value for tb_corp_auth_info.industry
     *
     * @mbggenerated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_corp_auth_info.is_delete
     *
     * @return the value of tb_corp_auth_info.is_delete
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_corp_auth_info.is_delete
     *
     * @param isDelete the value for tb_corp_auth_info.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_corp_auth_info.created_at
     *
     * @return the value of tb_corp_auth_info.created_at
     *
     * @mbggenerated
     */
    public Timestamp getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_corp_auth_info.created_at
     *
     * @param createdAt the value for tb_corp_auth_info.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_corp_auth_info.updated_at
     *
     * @return the value of tb_corp_auth_info.updated_at
     *
     * @mbggenerated
     */
    public Timestamp getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_corp_auth_info.updated_at
     *
     * @param updatedAt the value for tb_corp_auth_info.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }
}