package cn.tanziquan.produce.cole.data.domain;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class DdtalkAppCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public DdtalkAppCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyIsNull() {
            addCriterion("suite_key is null");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyIsNotNull() {
            addCriterion("suite_key is not null");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyEqualTo(String value) {
            addCriterion("suite_key =", value, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyNotEqualTo(String value) {
            addCriterion("suite_key <>", value, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyGreaterThan(String value) {
            addCriterion("suite_key >", value, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyGreaterThanOrEqualTo(String value) {
            addCriterion("suite_key >=", value, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyLessThan(String value) {
            addCriterion("suite_key <", value, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyLessThanOrEqualTo(String value) {
            addCriterion("suite_key <=", value, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyLike(String value) {
            addCriterion("suite_key like", value, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyNotLike(String value) {
            addCriterion("suite_key not like", value, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyIn(List<String> values) {
            addCriterion("suite_key in", values, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyNotIn(List<String> values) {
            addCriterion("suite_key not in", values, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyBetween(String value1, String value2) {
            addCriterion("suite_key between", value1, value2, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteKeyNotBetween(String value1, String value2) {
            addCriterion("suite_key not between", value1, value2, "suiteKey");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenIsNull() {
            addCriterion("suite_token is null");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenIsNotNull() {
            addCriterion("suite_token is not null");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenEqualTo(String value) {
            addCriterion("suite_token =", value, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenNotEqualTo(String value) {
            addCriterion("suite_token <>", value, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenGreaterThan(String value) {
            addCriterion("suite_token >", value, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenGreaterThanOrEqualTo(String value) {
            addCriterion("suite_token >=", value, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenLessThan(String value) {
            addCriterion("suite_token <", value, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenLessThanOrEqualTo(String value) {
            addCriterion("suite_token <=", value, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenLike(String value) {
            addCriterion("suite_token like", value, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenNotLike(String value) {
            addCriterion("suite_token not like", value, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenIn(List<String> values) {
            addCriterion("suite_token in", values, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenNotIn(List<String> values) {
            addCriterion("suite_token not in", values, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenBetween(String value1, String value2) {
            addCriterion("suite_token between", value1, value2, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTokenNotBetween(String value1, String value2) {
            addCriterion("suite_token not between", value1, value2, "suiteToken");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketIsNull() {
            addCriterion("suite_ticket is null");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketIsNotNull() {
            addCriterion("suite_ticket is not null");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketEqualTo(String value) {
            addCriterion("suite_ticket =", value, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketNotEqualTo(String value) {
            addCriterion("suite_ticket <>", value, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketGreaterThan(String value) {
            addCriterion("suite_ticket >", value, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketGreaterThanOrEqualTo(String value) {
            addCriterion("suite_ticket >=", value, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketLessThan(String value) {
            addCriterion("suite_ticket <", value, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketLessThanOrEqualTo(String value) {
            addCriterion("suite_ticket <=", value, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketLike(String value) {
            addCriterion("suite_ticket like", value, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketNotLike(String value) {
            addCriterion("suite_ticket not like", value, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketIn(List<String> values) {
            addCriterion("suite_ticket in", values, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketNotIn(List<String> values) {
            addCriterion("suite_ticket not in", values, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketBetween(String value1, String value2) {
            addCriterion("suite_ticket between", value1, value2, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andSuiteTicketNotBetween(String value1, String value2) {
            addCriterion("suite_ticket not between", value1, value2, "suiteTicket");
            return (Criteria) this;
        }

        public Criteria andEventTypeIsNull() {
            addCriterion("event_type is null");
            return (Criteria) this;
        }

        public Criteria andEventTypeIsNotNull() {
            addCriterion("event_type is not null");
            return (Criteria) this;
        }

        public Criteria andEventTypeEqualTo(String value) {
            addCriterion("event_type =", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotEqualTo(String value) {
            addCriterion("event_type <>", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeGreaterThan(String value) {
            addCriterion("event_type >", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeGreaterThanOrEqualTo(String value) {
            addCriterion("event_type >=", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLessThan(String value) {
            addCriterion("event_type <", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLessThanOrEqualTo(String value) {
            addCriterion("event_type <=", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLike(String value) {
            addCriterion("event_type like", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotLike(String value) {
            addCriterion("event_type not like", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeIn(List<String> values) {
            addCriterion("event_type in", values, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotIn(List<String> values) {
            addCriterion("event_type not in", values, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeBetween(String value1, String value2) {
            addCriterion("event_type between", value1, value2, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotBetween(String value1, String value2) {
            addCriterion("event_type not between", value1, value2, "eventType");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Short value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Short value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Short value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Short value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Short value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Short value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Short> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Short> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Short value1, Short value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Short value1, Short value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Timestamp value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Timestamp value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Timestamp value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Timestamp value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Timestamp value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Timestamp> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Timestamp> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Timestamp value1, Timestamp value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Timestamp value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Timestamp value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Timestamp value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Timestamp value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Timestamp value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Timestamp> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Timestamp> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Timestamp value1, Timestamp value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}