package cn.tanziquan.produce.cole.data.domain;

import java.io.Serializable;
import java.sql.Timestamp;

public class DdtalkApp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ddtalk_app.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ddtalk_app.suite_key
     *
     * @mbggenerated
     */
    private String suiteKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ddtalk_app.suite_token
     *
     * @mbggenerated
     */
    private String suiteToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ddtalk_app.suite_ticket
     *
     * @mbggenerated
     */
    private String suiteTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ddtalk_app.event_type
     *
     * @mbggenerated
     */
    private String eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ddtalk_app.is_delete
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ddtalk_app.created_at
     *
     * @mbggenerated
     */
    private Timestamp createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ddtalk_app.updated_at
     *
     * @mbggenerated
     */
    private Timestamp updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ddtalk_app.id
     *
     * @return the value of tb_ddtalk_app.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ddtalk_app.id
     *
     * @param id the value for tb_ddtalk_app.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ddtalk_app.suite_key
     *
     * @return the value of tb_ddtalk_app.suite_key
     *
     * @mbggenerated
     */
    public String getSuiteKey() {
        return suiteKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ddtalk_app.suite_key
     *
     * @param suiteKey the value for tb_ddtalk_app.suite_key
     *
     * @mbggenerated
     */
    public void setSuiteKey(String suiteKey) {
        this.suiteKey = suiteKey == null ? null : suiteKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ddtalk_app.suite_token
     *
     * @return the value of tb_ddtalk_app.suite_token
     *
     * @mbggenerated
     */
    public String getSuiteToken() {
        return suiteToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ddtalk_app.suite_token
     *
     * @param suiteToken the value for tb_ddtalk_app.suite_token
     *
     * @mbggenerated
     */
    public void setSuiteToken(String suiteToken) {
        this.suiteToken = suiteToken == null ? null : suiteToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ddtalk_app.suite_ticket
     *
     * @return the value of tb_ddtalk_app.suite_ticket
     *
     * @mbggenerated
     */
    public String getSuiteTicket() {
        return suiteTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ddtalk_app.suite_ticket
     *
     * @param suiteTicket the value for tb_ddtalk_app.suite_ticket
     *
     * @mbggenerated
     */
    public void setSuiteTicket(String suiteTicket) {
        this.suiteTicket = suiteTicket == null ? null : suiteTicket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ddtalk_app.event_type
     *
     * @return the value of tb_ddtalk_app.event_type
     *
     * @mbggenerated
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ddtalk_app.event_type
     *
     * @param eventType the value for tb_ddtalk_app.event_type
     *
     * @mbggenerated
     */
    public void setEventType(String eventType) {
        this.eventType = eventType == null ? null : eventType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ddtalk_app.is_delete
     *
     * @return the value of tb_ddtalk_app.is_delete
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ddtalk_app.is_delete
     *
     * @param isDelete the value for tb_ddtalk_app.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ddtalk_app.created_at
     *
     * @return the value of tb_ddtalk_app.created_at
     *
     * @mbggenerated
     */
    public Timestamp getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ddtalk_app.created_at
     *
     * @param createdAt the value for tb_ddtalk_app.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ddtalk_app.updated_at
     *
     * @return the value of tb_ddtalk_app.updated_at
     *
     * @mbggenerated
     */
    public Timestamp getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ddtalk_app.updated_at
     *
     * @param updatedAt the value for tb_ddtalk_app.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }
}