environments:
    db:
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://qdm150698491.my3w.com/qdm150698491_db?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&defaultBatchValue=1000
        #jdbcUrl: jdbc:mysql://127.0.0.1/cole
        jdbcUser: qdm150698491
        jdbcPwd: qdm150698491
    build:
         path: /data/produce.cole/build
    ddtalk:
        token: 123456
        encodingAesKey: 4g5j64qlyl3zvetqxz5jiocdr586fn2zvjpa8zls3ij
        createSuiteKey: suite4xxxxxxxxxxxxxxx


spring:
    thymeleaf:
        cache: false