environments:
    db:
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://qdm107498573.my3w.com/qdm107498573_db?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&defaultBatchValue=1000
        #jdbcUrl: jdbc:mysql://127.0.0.1/cole
        jdbcUser: qdm107498573
        jdbcPwd: qdm107498573
spring:
    thymeleaf:
        cache: false