environments:
    db:
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://qdm150698491.my3w.com/qdm150698491_db?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&defaultBatchValue=1000
        #jdbcUrl: jdbc:mysql://127.0.0.1/cole
        jdbcUser: qdm150698491
        jdbcPwd: qdm150698491
    build:
         path: /data/produce.cole/build
    ddtalk:
        token: zhigangtan00001
        encodingAesKey: dwlq23ebzgb90woi8lzuldaim85arxcqvtat32ovwct
        createSuiteKey: suite4xxxxxxxxxxxxxxx


spring:
    thymeleaf:
        cache: false