package cn.tanziquan.produce.cole.data.persistence;

import cn.tanziquan.produce.cole.data.domain.AppInfo;
import cn.tanziquan.produce.cole.data.domain.AppInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    int countByExample(AppInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    int deleteByExample(AppInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    int insert(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    int insertSelective(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    List<AppInfo> selectByExample(AppInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    AppInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppInfo record, @Param("example") AppInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppInfo record, @Param("example") AppInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppInfo record);
}