package cn.tanziquan.produce.cole.data.persistence;

import cn.tanziquan.produce.cole.data.domain.ColeRequestBody;
import cn.tanziquan.produce.cole.data.domain.ColeRequestBodyCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColeRequestBodyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    int countByExample(ColeRequestBodyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    int deleteByExample(ColeRequestBodyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    int insert(ColeRequestBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    int insertSelective(ColeRequestBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    List<ColeRequestBody> selectByExample(ColeRequestBodyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    ColeRequestBody selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ColeRequestBody record, @Param("example") ColeRequestBodyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ColeRequestBody record, @Param("example") ColeRequestBodyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ColeRequestBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cole_request_body
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ColeRequestBody record);
}