package cn.tanziquan.produce.cole.data.persistence;

import cn.tanziquan.produce.cole.data.domain.CorpAuthInfo;
import cn.tanziquan.produce.cole.data.domain.CorpAuthInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CorpAuthInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    int countByExample(CorpAuthInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    int deleteByExample(CorpAuthInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    int insert(CorpAuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    int insertSelective(CorpAuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    List<CorpAuthInfo> selectByExample(CorpAuthInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    CorpAuthInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CorpAuthInfo record, @Param("example") CorpAuthInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CorpAuthInfo record, @Param("example") CorpAuthInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CorpAuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_corp_auth_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CorpAuthInfo record);
}