package cn.tanziquan.produce.cole.data.persistence;

import cn.tanziquan.produce.cole.data.domain.DdtalkApp;
import cn.tanziquan.produce.cole.data.domain.DdtalkAppCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DdtalkAppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    int countByExample(DdtalkAppCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    int deleteByExample(DdtalkAppCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    int insert(DdtalkApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    int insertSelective(DdtalkApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    List<DdtalkApp> selectByExample(DdtalkAppCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    DdtalkApp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DdtalkApp record, @Param("example") DdtalkAppCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DdtalkApp record, @Param("example") DdtalkAppCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DdtalkApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_app
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DdtalkApp record);
}