package cn.tanziquan.produce.cole.data.persistence;

import cn.tanziquan.produce.cole.data.domain.DdtalkCropAuth;
import cn.tanziquan.produce.cole.data.domain.DdtalkCropAuthCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DdtalkCropAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    int countByExample(DdtalkCropAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    int deleteByExample(DdtalkCropAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    int insert(DdtalkCropAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    int insertSelective(DdtalkCropAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    List<DdtalkCropAuth> selectByExample(DdtalkCropAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    DdtalkCropAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DdtalkCropAuth record, @Param("example") DdtalkCropAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DdtalkCropAuth record, @Param("example") DdtalkCropAuthCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DdtalkCropAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ddtalk_corp_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DdtalkCropAuth record);
}